sudo: false

os:
  - linux

language: node_js
node_js: lts/*

env:
  global:
    - FLUTTER_TEST=true
  matrix:
    - ONLY_RUN_CODE_VERSION=STABLE ONLY_RUN_DART_VERSION=STABLE

addons:
  apt:
    packages:
      - libsecret-1-dev
      - libstdc++6
      - gcc-4.8

script:
  - export CXX="g++-4.8" CC="gcc-4.8" DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10

